### ISSUE TITLE
我不是很能理解“Sequence contains no elements”的意思

### ISSUE THREAD

**Issue by 2991387368** [Neskol/MaichartConverter#13]
我在执行simai转ma2时几乎每个铺面都会出现这个报错，但是相同的操作部分铺面又不会出现这种问题，当相同的铺面使用MaiConverter时进行simai到ma2的转换时并不会报错。
![无标题](https://github.com/Neskol/MaichartConverter/assets/81029100/9c62b36f-7ef8-491d-ac37-06e952524666)

同时有些铺面还会出现如“The input string 'f' was not in a correct format.”的报错，但检查铺面并未发现问题
![无标题1](https://github.com/Neskol/MaichartConverter/assets/81029100/74d3bdac-848f-4f1e-8080-11080aeb1354)

**Comment by Neskol** [comment]
介意提供下你的Simai文件吗？没有严格按照simai规范书写的谱子可能会引发奇怪的错误

**Comment by SakuraiFang** [comment]
这里似乎有同样问题
![issueReport](https://github.com/Neskol/MaichartConverter/assets/11800085/f06c7af6-5253-43ae-9dd7-b923d5259e8c)

**Comment by 2991387368** [comment]
> 介意提供下你的Simai文件吗？没有严格按照simai规范书写的谱子可能会引发奇怪的错误
[ちんこ音頭2022 (2).zip](https://github.com/Neskol/MaichartConverter/files/13785386/2022.2.zip)
[test.zip](https://github.com/Neskol/MaichartConverter/files/13785390/test.zip)


图1中的铺面在test.zip里面，图2中的铺面在另一个压缩包里面

**Comment by 2991387368** [comment]
然后这种并非是在当前版本的MaichartConverter出现，在上个版本中就出现了这种问题，但那是比较早的事情，文件不太好找

**Comment by LoaderTime** [comment]
> 我在执行simai转ma2时几乎每个铺面都会出现这个报错，但是相同的操作部分铺面又不会出现这种问题，当相同的铺面使用MaiConverter时进行simai到ma2的转换时并不会报错。

似乎有些铺面文件确实是只能在另一端可以转换，但是大部分都是两个都转换不了
三种情况的铺面文件：
[charts.zip](https://github.com/Neskol/MaichartConverter/files/13800243/charts.zip)

可能原因是多数Viewer和模拟器都有自己的编译库，所以表现可能不尽相同（连语法都可能不同），因此会多出来一些**奇怪**的语法什么的... （信息来自：https://github.com/donmai-me/MaiConverter/issues/14）

**Comment by STLFrisk** [comment]
我也有同样的问题，求助
[Apollo.zip](https://github.com/Neskol/MaichartConverter/files/13800974/Apollo.zip)

**Comment by STLFrisk** [comment]
还有
[raputa.zip](https://github.com/Neskol/MaichartConverter/files/13800976/raputa.zip)

**Comment by STLFrisk** [comment]
以下是错误报告
![image](https://github.com/Neskol/MaichartConverter/assets/122624196/e9f86497-c662-45f5-a6e7-0516d1952fdf)
![image](https://github.com/Neskol/MaichartConverter/assets/122624196/c0d9853d-0a34-40d6-b4d0-d4107e009761)

**Comment by 2991387368** [comment]
> > 我在执行simai转ma2时几乎每个铺面都会出现这个报错，但是相同的操作部分铺面又不会出现这种问题，当相同的铺面使用MaiConverter时进行simai到ma2的转换时并不会报错。
> 
> 似乎有些铺面文件确实是只能在另一端可以转换，但是大部分都是两个都转换不了 三种情况的铺面文件： [charts.zip](https://github.com/Neskol/MaichartConverter/files/13800243/charts.zip)
> 
> 可能原因是多数Viewer和模拟器都有自己的编译库，所以表现可能不尽相同（连语法都可能不同），因此会多出来一些**奇怪**的东西语法什么的...（信息来自：[donmai-me/MaiConverter#14](https://github.com/donmai-me/MaiConverter/issues/14) ）

可能有这部分问题，但我觉得不只是这样的问题，因为之前转换一个只有简单的tap和slider的铺面也出现了问题依旧出现了问题，其次我觉得可以如另一个工具一样的，转铺失败会指出铺面那里不能转换

**Comment by STLFrisk** [comment]
另外一个转谱工具可以指一下路吗？非常感谢！

**Comment by Neskol** [comment]
确认了一下，我想先简单提一下`CompileSimai`的具体功能 - 将Simai文件中的特定难度转换为ma2。
ma2文件只包含单一难度谱面并由music.xml定义其他信息，所以Simai到ma2实际上是一个一对多的关系。这部分转换超出了`CompileSimai`命令的初衷，故暂时没有支持。
Simai包含的难度从`&inote_1`开始。如果用户没有指定难度，那么程序会从难度1开始查找第一个谱面。如果没有找到任何`&inote_X=`那么程序自然找不到第一个谱面，就会报`Sequence contains no element`错误。
 @2991387368 提供的test,zip中包含的第一个文件`maidata.txt`实际上是没有问题的：难度5不为空，那么程序就能正常运转。
![image](https://github.com/Neskol/MaichartConverter/assets/47587132/55b30496-e3d6-4a56-8291-462f9c63220a)
然而第二个文件不包含任何其他信息，那么程序由于找不到任何`&inote_X=`开头的字段，自然也无法确认难度，结果也就没有任何谱面被转换。在我这里重现了同样的问题：
![image](https://github.com/Neskol/MaichartConverter/assets/47587132/8afa1ad4-06ef-41ef-aecc-cdb8aca58992)
当然，无谱面信息的纯Simai文件是可以被底层库`MaiLib`解析的，只是`MaichartConverter`暂时没有加入这个功能 - 预定将会在下一个功能更新加入。
另外一个问题可能是文件上传错了，没有找到KnightRider的谱面，还请再确认一下，倒是报了不同的错误：
![image](https://github.com/Neskol/MaichartConverter/assets/47587132/5eba34e1-8d33-4ab5-a416-3b5252065aba)
由于`^`星星解析加入的较晚，这个倒是真的bug，将会在下一个功能更新修复。

**Comment by Neskol** [comment]
以上内容已经确认在本地修复，本issue将会在pr之后关闭
