### ISSUE TITLE
fes配置转译问题

### ISSUE THREAD

**Issue by Sodiumsss** [Neskol/MaichartConverter#15]
MaichartConverter @ 8a35899
MaiLib @ d1644a1

maidata：
(170)
{1},,,,{8},,,,3,3,8,B6/B7,
{8}7-2-7[8:1],,,,7-2-7b[8:1],,,,7-2b[8:1],,,,7bx,,,,
{8},,A1,,,,A4f,,,,,,,,,,
{8},2-5[8:1],1,2,7-4[8:1],8-3[8:1],7,8,

问题：A4f不闪光，7bx没有套，7-2-7b绝赞连续星星不是绝赞星星，7-2b也是绝赞星星没有绝赞

MaichartConverter CompileSimai -p maidata.txt

ma2：
TAP	4	192	2
TAP	4	240	2
TAP	4	288	7
TTP	4	336	5	B	0	M1
TTP	4	336	6	B	0	M1
STR	5	0	6
SI_	5	0	6	96	24	1
SI_	5	120	1	0	24	6
STR	5	192	6
SI_	5	192	6	96	24	1
SI_	5	312	1	0	24	6
STR	6	0	6
SI_	6	0	6	96	48	1
BRK	6	192	6
TTP	7	96	0	A	0	M1
TTP	7	288	3	A	1	M1
STR	9	48	1
SI_	9	48	1	96	48	4
TAP	9	96	0
TAP	9	144	1
STR	9	192	6
SI_	9	192	6	96	48	3
STR	9	240	7
SI_	9	240	7	96	48	2
TAP	9	288	6
TAP	9	336	7

**Comment by Neskol** [comment]
Festival配置需要额外增加`-f Ma2_104`参数

**Comment by Sodiumsss** [comment]
> Festival配置需要额外增加`-f Ma2_104`参数

谢谢
