### ISSUE TITLE
CompileSimai中部分Utage配置出现问题

### ISSUE THREAD

**Issue by RevoBleug** [Neskol/MaichartConverter#17]
使用CompileSimai进行simai转ma2时出现问题，报错如下：
Simai Parser encountered an error while parsing after bar 1 tick 0 when parsing token v5[3.5#32:1] in each group “{16}, 3_, v5[3.5#32:1]”:
The input string '3.5#32' was not in a correct format.

**Comment by Neskol** [comment]
目前`MaiLib`暂未支持`BPM#Measure:Count`写法，对该写法的支持正在编写。请暂时考虑使用秒数来编写不规则时长星星，谢谢！
