### ISSUE TITLE
fes特性slide转ma2时长有问题

### ISSUE THREAD

**Issue by YTSakura233** [Neskol/MaichartConverter#19]
fes新特性的slide（1-4-6[8:1]这种）时长转出来有问题，maidata写的是时长8:1可是转出来所有的时长都是1:1 转ma2的时候用了 -f Ma2_104

**Comment by Neskol** [comment]
您好，请问您使用的程序版本是否为`1.0.7.0`

**Comment by YTSakura233** [comment]
> 您好，请问您使用的程序版本是否为`1.0.7.0`

是的 使用的是1.0.7.0

**Comment by Neskol** [comment]
请问是否可以提供完整的maidata？我这边没有复现问题
<img width="365" alt="Screenshot 2024-02-26 at 09 56 46" src="https://github.com/Neskol/MaichartConverter/assets/47587132/57cd2881-db6a-4782-9097-656d192d2194">

<img width="354" alt="Screenshot 2024-02-26 at 09 58 27" src="https://github.com/Neskol/MaichartConverter/assets/47587132/2524d6e3-abd1-42fd-948e-f4d16564f01e">

<img width="305" alt="Screenshot 2024-02-26 at 09 59 49" src="https://github.com/Neskol/MaichartConverter/assets/47587132/d3cdcddf-9293-4368-981e-60402247548a">

**Comment by YTSakura233** [comment]
[https://pan.baidu.com/s/1VSl52K97qti3HYGjMXWRKg?pwd=z3b1 ](视频)
[maidata.txt](https://github.com/Neskol/MaichartConverter/files/14404376/maidata.txt)
[result.txt](https://github.com/Neskol/MaichartConverter/files/14404380/result.txt)
我录制了两个视频，分别是在Majdata以及maimaidx1.40里面的对比，明显时长是不一样的（1.35也试了时长也不对）
maidata以及ma2（result.txt）也上传了。
![image](https://github.com/Neskol/MaichartConverter/assets/102224159/d4bb9f81-3bdb-46ab-b4c5-41da51c9cd56)
![image](https://github.com/Neskol/MaichartConverter/assets/102224159/787c086d-b5aa-4313-927f-9740307faf0d)
