### ISSUE TITLE
转谱发生错误并闪退

### ISSUE THREAD

**Issue by Tsurumaki-Kokoro** [Neskol/MaichartConverter#3]
![QQ图片20220616220528](https://user-images.githubusercontent.com/61814901/174088137-1283fbbb-f636-4634-ad9f-8b39efe8774f.png)
如图所示

**Comment by Neskol** [comment]
您好，我在这里无法复现该bug：我使用的xml没有报错。如果是自行编译，请拉取更改后重新编译，谢谢！
