### ISSUE TITLE
Windows 1.04版本发生闪退

### ISSUE THREAD

**Issue by LoaderTime** [Neskol/MaichartConverter#4]
在我打开文件内的"MaichartConverter.exe"时发生了闪退（已解压），随后我尝试在Viusal Studio上运行它时出现了错误代码（-1）
如下图所示
![visual studios](https://user-images.githubusercontent.com/129403212/228858055-71825298-6bbe-45e1-8f85-26394bf19f77.PNG)
但是奇怪的是，1.02版本可以运行

**Comment by Neskol** [comment]
从版本1.0.4开始程序转变为需要传入参数才可以正常运行，所以直接打开相当于没有传入参数。可以在命令行中使用.\MaichartConverter.exe help CompileDatabase查看参数说明，或者直接clone repo并使用VSCode/Visual Studio打开，修改启动参数的对应路径。
具体方法如下：
在程序的位置打开终端并输入以下命令:
`./MaichartConverter help CompileDatabase`
程序会输出所需要的对应参数。
