### ISSUE TITLE
V字星星反向了

### ISSUE THREAD

**Issue by Remilia1023** [Neskol/MaichartConverter#5]
将maidata转成ma2之后V字星星的SLL会变成SLR，SLR会变成SLL

**Comment by Neskol** [comment]
您好 是所有的曲目吗 ma2和simai的转换逻辑不一样 不太好确认

**Comment by Remilia1023** [comment]
不太看github消息所以一直没回😭，是吧，我转了大概10首都有这个问题

**Comment by Neskol** [comment]
已经确认到了，正在修改，将会在近期与MaiLib 1.0.6一起更新。感谢您的支持！

**Comment by Remilia1023** [comment]
对了，这个是不是不支持fes谱QAQ

**Comment by Neskol** [comment]
正在[MaiLib PR#22](https://github.com/Neskol/MaiLib/pull/22)测试，有兴趣的话可以帮忙审议一下，非常感谢！
