### ISSUE TITLE
个人问题

### ISSUE THREAD

**Issue by victor-maxwill** [Neskol/MaichartConverter#6]
总提示我access to the path is denied
网上找了各种方法手段没一个管用的
卡在这了。。。
![wx_camera_1699414461601](https://github.com/Neskol/MaichartConverter/assets/62059245/0b3667da-e439-4335-8ed6-8090c30b0050)

**Comment by Neskol** [comment]
请您尝试把谱面文件复制到其他文件夹（比如您电脑上的文档文件夹）再尝试，可能是权限问题

**Comment by victor-maxwill** [comment]
> 请您尝试把谱面文件复制到其他文件夹（比如您电脑上的文档文件夹）再尝试，可能是权限问题

我已试过，无用。
无论谱面复制到哪个地方，都没有权限。
在文件夹选项里更改安全设置也没用。

**Comment by blobber5678** [comment]
I'm having the same issue as well, exact same error code. For some reason it worked on another computer running Windows 11. Not sure why it is.

**Comment by victor-maxwill** [comment]
> I'm having the same issue as well, exact same error code. For some reason it worked on another computer running Windows 11. Not sure why it is.

请问你的win10系统是家庭版吗
